name: sfx
description: SFX for new games.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audiofileplayer: ^1.1.1
  cupertino_icons: ^0.1.3
  awesome_dialog: ^1.2.0
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  image_picker: ^0.6.7+4
  file_picker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

